sudo: required
dist: xenial
language: cpp
cache:
  ccache: true
git:
  depth: 1
addons:
  apt:
    packages:
      - cmake
before_install:
  - bash .travis.sh

#env:
#  global:

jobs:
  include:
    - name: "Library, Examples, Tools, Apps"
      compiler: gcc
      env: TASK="build"
      script: bash .travis.sh $TASK

notifications:
  email: false


